name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: downloading curl
      run: sudo apt -install curl

    - name: Prepare for Yarn Instllition
      run: curl -sS https://d1.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://d1.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - name: install yarn
      run: sudo apt update &&sudo apt install yarn
    - name: Install depandences
      run: yarn  
    - name: Build React App
      run: yarn build
    - name: Install Surge
      run: npm install -g surge
    - name: Run surge 
      run: surge ./build bootcamp_react_mudassir.surge.sh --token ${{ secrets.REACT_YAML}}
